"""Part II rederivation machinery: class extraction, algebra dims, certificates."""
import numpy as np
from kwl import wl2, ts_partition, cfi, _canon

P1, P2 = 99999989, 99999971  # primes ~1e8; safe for n<=112 matmul in int64

def classes(A):
    """Return (g labels, list of 0/1 class matrices, types) with types in
    {'diag','thin','thick'} per class."""
    g = wl2(A)
    K = g.max() + 1
    mats, types = [], []
    n = A.shape[0]
    diag = np.eye(n, dtype=bool)
    for c in range(K):
        M = (g == c).astype(np.int64)
        mats.append(M)
        if (M[diag].sum() > 0):
            types.append('diag')
        elif ((M > 0) <= (A > 0)).all():
            types.append('thin')
        else:
            types.append('thick')
    return g, mats, types

def _rref_add(basis, vec, p):
    """Reduce vec (1-D int64 mod p) against basis rows (list of (pivot, row));
    add if independent. Returns True if added."""
    v = vec % p
    for piv, row in basis:
        if v[piv]:
            v = (v - v[piv] * row) % p
    nz = np.nonzero(v)[0]
    if len(nz) == 0:
        return False
    piv = nz[0]
    v = (v * pow(int(v[piv]), p - 2, p)) % p
    basis.append((piv, v))
    return True

def algebra_dim(gens, n, unital=True, p=P1, maxdim=None):
    """Dimension of the unital algebra generated by gens (list of int matrices)."""
    basis = []
    queue = []
    def add(M):
        if _rref_add(basis, (M % p).ravel(), p):
            queue.append(M % p)
            return True
        return False
    if unital:
        add(np.eye(n, dtype=np.int64))
    for G in gens:
        add(G)
    gmods = [G % p for G in gens]
    i = 0
    while i < len(queue):
        X = queue[i]; i += 1
        for G in gmods:
            add((X @ G) % p)
            add((G @ X) % p)
        if maxdim and len(basis) >= maxdim:
            break
    return len(basis)

def arc_algebra_dim(A):
    g, mats, types = classes(A)
    gens = [M for M, t in zip(mats, types) if t == 'thin']
    d1 = algebra_dim(gens, A.shape[0], p=P1)
    d2 = algebra_dim(gens, A.shape[0], p=P2)
    assert d1 == d2, (d1, d2)
    return d1, len(mats)

def walk_closure_dim(A):
    """Dim of smallest M-closed (no Hadamard) space containing I,A,J:
    span{A^i} + span{A^i J A^j}."""
    n = A.shape[0]
    J = np.ones((n, n), dtype=np.int64)
    basis = []
    def add(M):
        return _rref_add(basis, (M % P1).ravel(), P1)
    X = np.eye(n, dtype=np.int64)
    while add(X):
        X = (X @ A) % P1
    left = np.array(J)
    while True:
        anyadd = add(left % P1)
        Y = np.array(left)
        added_inner = False
        while True:
            Y = (Y @ A) % P1
            if add(Y): added_inner = True
            else: break
        if not anyadd and not added_inner:
            break
        left = (A @ left) % P1
    return len(basis)

def cert_check(A, mergepairs):
    """Verify the stall certificate: pi = coherent partition with the given
    g-class pairs merged. Check closure under multiplication by every coherent
    arc class (both sides), Hadamard/transpose closure, I,A,J membership.
    Returns dict of results. Exact integer arithmetic."""
    g, mats, types = classes(A)
    K = len(mats)
    relabel = {c: c for c in range(K)}
    for a, b in mergepairs:
        relabel[b] = relabel[a]
    pi = np.vectorize(relabel.get)(g)
    pi = _canon(pi)
    B = pi.max() + 1
    blocks = [(pi == c).astype(np.int64) for c in range(B)]
    arcs = [M for M, t in zip(mats, types) if t == 'thin']
    def blockconst(M):
        for bl in blocks:
            vals = M[bl > 0]
            if len(vals) and vals.min() != vals.max():
                return False
        return True
    mult_ok = all(blockconst(R @ bl) and blockconst(bl @ R)
                  for R in arcs for bl in blocks)
    transp_ok = all(blockconst(bl.T) for bl in blocks)
    n = A.shape[0]
    IAJ_ok = blockconst(np.eye(n, dtype=np.int64)) and blockconst(A) \
        and blockconst(np.ones((n, n), dtype=np.int64))
    # coherence of the merged partition: count violating (a,b,c) triples
    viol = 0
    for X in blocks:
        for Y in blocks:
            Pr = X @ Y
            for bl in blocks:
                vals = Pr[bl > 0]
                if len(vals) and vals.min() != vals.max():
                    viol += 1
    return dict(nblocks=B, mult_closed=mult_ok, transpose_closed=transp_ok,
                IAJ=IAJ_ok, coherence_violations=viol)

def merged_pair(A, verts=None):
    """Locate l-classes containing >1 g-class; return list of
    (g-class ids, sizes, reps, types)."""
    g = wl2(A); l = ts_partition(A)
    n = A.shape[0]
    from collections import defaultdict
    m = defaultdict(set)
    for x in range(n):
        for y in range(n):
            m[l[x, y]].add(g[x, y])
    out = []
    _, mats, types = classes(A)
    for k, v in m.items():
        if len(v) > 1:
            info = []
            for gc in sorted(v):
                xs, ys = np.where(g == gc)
                rep = (verts[xs[0]], verts[ys[0]]) if verts else (xs[0], ys[0])
                info.append((gc, len(xs), rep, types[gc]))
            out.append(info)
    return out
